"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import error as components_error
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class CreatePetsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    error: Optional[components_error.Error] = dataclasses.field(default=None)
    r"""unexpected error"""
    

