"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import error as components_error
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import pet as components_pet
from typing import Optional


@dataclasses.dataclass
class ShowPetByIDRequest:
    pet_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': False }})
    r"""The id of the pet to retrieve"""
    



@dataclasses.dataclass
class ShowPetByIDResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    error: Optional[components_error.Error] = dataclasses.field(default=None)
    r"""unexpected error"""
    pet: Optional[components_pet.Pet] = dataclasses.field(default=None)
    r"""Expected response to a valid request"""
    

